# -*- coding: utf-8 -*-
"""mul

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LnGsz5lVa2ubl7SokPd5c8lOdD6MT2bP
"""

def mul(num1, num2):
    print('Result is: ', num1 * num2)